-- =============================================================================
-- 007_security_hardening.sql (REVERT TO CLIENT-SIDE E2EE PREP)
-- 
-- This script removes the database-side "Transparent" encryption which was
-- causing permission and save errors. It restores standard tables and 
-- prepares the schema for Client-Side End-to-End Encryption (E2EE).
-- =============================================================================

BEGIN;

-- 1. CLEANUP BROKEN VIEWS & TRIGGERS
DROP VIEW IF EXISTS public.transactions CASCADE;
DROP VIEW IF EXISTS public.cards CASCADE;
DROP VIEW IF EXISTS public.notes CASCADE;

DROP FUNCTION IF EXISTS public.tr_handle_transactions() CASCADE;
DROP FUNCTION IF EXISTS public.tr_handle_cards() CASCADE;
DROP FUNCTION IF EXISTS public.tr_handle_notes() CASCADE;
DROP FUNCTION IF EXISTS public.get_encryption_key() CASCADE;

-- 2. RESTORE TABLES (IF THEY WERE RENAMED)
DO $$
BEGIN
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'transactions_base') THEN
    ALTER TABLE public.transactions_base RENAME TO transactions;
  END IF;
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'cards_base') THEN
    ALTER TABLE public.cards_base RENAME TO cards;
  END IF;
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'notes_base') THEN
    ALTER TABLE public.notes_base RENAME TO notes;
  END IF;
END $$;

-- 3. RESET COLUMNS TO TEXT
-- We use TEXT to store the E2EE ciphertext generated by the browser.
ALTER TABLE public.transactions ALTER COLUMN note TYPE TEXT USING note::text;
ALTER TABLE public.cards ALTER COLUMN number TYPE TEXT USING number::text;
ALTER TABLE public.cards ALTER COLUMN expiry TYPE TEXT USING expiry::text;
ALTER TABLE public.notes ALTER COLUMN content TYPE TEXT USING content::text;

-- 4. PREPARE PROFILES FOR CLIENT-SIDE E2EE
-- encryption_salt: Used to derive a unique key per user.
-- encryption_check: Used to verify the user entered the correct PIN/Password.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS encryption_salt TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS encryption_check TEXT;

-- 5. SECURE USER LOOKUP RPCs (KEEP THESE - THEY ARE SAFE)
CREATE OR REPLACE FUNCTION public.get_user_id_by_email(email_to_find TEXT)
RETURNS TABLE (id UUID) 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN; END IF;
  RETURN QUERY SELECT u.id FROM auth.users u WHERE u.email = LOWER(email_to_find);
END;
$$;

CREATE OR REPLACE FUNCTION public.get_user_email_by_id(id_to_find UUID)
RETURNS TABLE (email TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN; END IF;
  IF EXISTS (
    SELECT 1 FROM public.notifications n
    WHERE (n.sender_id = auth.uid() AND n.user_id = id_to_find)
       OR (n.sender_id = id_to_find AND n.user_id = auth.uid())
  ) OR id_to_find = auth.uid() THEN
    RETURN QUERY SELECT u.email::TEXT FROM auth.users u WHERE u.id = id_to_find;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_user_id_by_email(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_email_by_id(UUID) TO authenticated;

-- 6. RESTORE STANDARD RLS POLICIES
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users own transactions" ON public.transactions;
CREATE POLICY "Users own transactions" ON public.transactions FOR ALL USING (auth.uid() = user_id);

ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users own cards" ON public.cards;
CREATE POLICY "Users own cards" ON public.cards FOR ALL USING (auth.uid() = user_id);

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users own notes" ON public.notes;
CREATE POLICY "Users own notes" ON public.notes FOR ALL USING (auth.uid() = user_id);

COMMIT;
