import { ShieldQuestion, Home, Search } from 'lucide-react'
import Link from 'next/link'

export default function NotFound() {
  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-[#000000]">
      {/* Background Glow */}
      <div className="fixed inset-0 pointer-events-none opacity-20">
        <div className="absolute top-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-600 rounded-full blur-[120px]" />
        <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] bg-purple-600 rounded-full blur-[120px]" />
      </div>

      <div className="relative z-10 w-full max-w-2xl animate-in fade-in zoom-in duration-500">
        <div className="flex flex-col items-center text-center space-y-8">
          <div className="relative">
             <div className="w-24 h-24 rounded-3xl bg-white/5 border border-white/10 flex items-center justify-center backdrop-blur-3xl shadow-2xl">
                <ShieldQuestion className="text-blue-500 w-12 h-12" />
             </div>
             <div className="absolute -top-2 -right-2 px-3 py-1 bg-blue-500 text-white text-[10px] font-black uppercase tracking-widest rounded-full shadow-lg">
                404 Not Found
             </div>
          </div>

          <div className="space-y-3">
            <h1 className="text-4xl md:text-5xl font-black tracking-tight text-white leading-tight">
              The requested record <br/> could not be found.
            </h1>
            <p className="text-zinc-400 max-w-md mx-auto text-sm leading-relaxed">
              The vault address you entered does not exist or has been relocated. Please verify the URL or return to the dashboard.
            </p>
          </div>

          {/* Vercel Style diagnostic box */}
          <div className="w-full bg-white/[0.03] border border-white/10 rounded-3xl overflow-hidden backdrop-blur-xl">
             <div className="p-8 text-center space-y-4">
                <div className="mx-auto w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
                   <Search className="w-6 h-6 text-zinc-500" />
                </div>
                <div className="space-y-1">
                   <p className="text-sm font-bold text-white uppercase tracking-widest">Resource Not Located</p>
                   <p className="text-[10px] text-zinc-500 font-mono">STATUS_CODE: 404_DEPLOYMENT_NOT_FOUND</p>
                </div>
             </div>
             
             <div className="px-6 py-4 bg-white/[0.02] border-t border-white/5 flex items-center justify-between">
                <Link 
                  href="https://vercel.com/docs/concepts/deployments/overview" 
                  target="_blank"
                  className="text-[9px] font-bold text-zinc-500 hover:text-white transition-colors uppercase tracking-widest"
                >
                  Deployment Docs
                </Link>
                <span className="text-[9px] font-medium text-zinc-700 uppercase tracking-tighter">Generated by Vercel Origin Handler</span>
             </div>
          </div>

          <div className="flex flex-col sm:flex-row items-center gap-4 w-full max-w-sm">
            <Link 
              href="/dashboard"
              className="w-full h-14 rounded-2xl bg-white text-black font-bold text-sm flex items-center justify-center gap-2 hover:bg-zinc-200 active:scale-[0.98] transition-all"
            >
              <Home size={18} />
              Return Dashboard
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
